name: CI
on:
  push:
    branches: [dev, "renovate/*"]
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Build
    if: github.event_name != 'pull_request' || !startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: yarn

      - name: Install and build
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run build
